### ISSUE TITLE
How is the sound created

### ISSUE THREAD

**Issue by jcubic** [ZacharyL2/KeyEcho#1]
I hope it's ok to ask this. I just found about your project, and I'm wondering where those sounds came from?

**Comment by ZacharyL2** [comment]
Hi, thanks for your interest!

The sounds for KeyEcho are in this [directory](https://github.com/ZacharyL2/KeyEcho/tree/master/src-tauri/resources). They are generated based on the [sounds](https://github.com/hainguyents13/mechvibes/tree/master/src/audio) from the [mechvibes](https://github.com/hainguyents13/mechvibes) library. 

I plan to add a feature for custom sounds soon to give more options.

**Comment by ZacharyL2** [comment]
Two years ago, you asked how KeyEcho produces its sounds. The 1.0 release rewrote the audio hot path: sound packs are predecoded when selected, playback reuses shared sample buffers, and the reference lookup dropped from 1,184 ns to 43.5 ns. The implementation notes are here: https://github.com/ZacharyL2/KeyEcho/blob/main/docs/performance.md. Thanks for taking an early interest in this part of the project.
