### ISSUE TITLE
Version v0.0.3 doesn't work on MacOS

### ISSUE THREAD

**Issue by AlekseyPleshkov** [ZacharyL2/KeyEcho#14]
Hello! Thank for this application 🤙

Just notice, that new version (0.0.3) doesn't play sound on MacOS. 
If install previous version (0.0.2), everything will work fine.

M1, MacOS Sonoma 14.5.

**Comment by ZacharyL2** [comment]
See #9. This may be a problem with permissions on MacOS after an automatic update. I'll check that.

**Comment by AlekseyPleshkov** [comment]
> See #9. This may be a problem with permissions on MacOS after an automatic update. I'll check that.

Yes, remove and add permission - works for me. Thx!

**Comment by ZacharyL2** [comment]
You got KeyEcho working by removing and re-adding its Input Monitoring permission. The KeyEcho 1.0 macOS builds now have stable signing and notarization, which should reduce permission identity changes between releases. If you are still using the app, I would be interested to know whether the permission survives the v1 update.
