### ISSUE TITLE
[bug] Trojan

### ISSUE THREAD

**Issue by emoss08** [ZacharyL2/KeyEcho#16]
### OS

Windows

### OS Version

10.0.22631

### Describe the bug

Another trojan

![image](https://github.com/ZacharyL2/KeyEcho/assets/66630775/0c9a496d-4c3c-45b5-8997-5a3cc3d40cd6)

**Comment by switchblade34** [comment]
probably a false positive since it's keylogging in a way ig

**Comment by flacial** [comment]
Never trust a software Ad from Twitter other than Brilliant.

**Comment by ZacharyL2** [comment]
@emoss08 To centrally address issues caused by unsigned code, I have opened a new issue #18. Please continue to raise any questions there. I will close this issue. Thank you for your contribution!
