### ISSUE TITLE
Toggle for volume rocker sound 

### ISSUE THREAD

**Issue by switchblade34** [ZacharyL2/KeyEcho#17]
### Describe the problem

I don't need the key sound for when I increase/decrease my volume as I don't really have a rocker on my keyboard. 

### Describe the solution you'd like

A simple toggle to turn on/off the key sound when changing the volume should be enough.

**Comment by ZacharyL2** [comment]
Thank you for your suggestion, I almost forgot about it. Actually, the backend already supports volume control.

I will include this feature in the next version, so stay tuned.

**Comment by ZacharyL2** [comment]
@switchblade34 I've just [released 0.0.4](https://github.com/ZacharyL2/KeyEcho/releases/tag/v0.0.4), now you should be able to adjust the volume of KeyEcho.

**Comment by switchblade34** [comment]
Hey, thanks for adding volume control but this is not what I was talking about in the feature request. Maybe I didn't explain it the right way as English isn't my first language so I'll explain it in more detail:

My keyboard has a scroll wheel that changes the volume on my laptop. Whenever I change the system volume using the scroll wheel, KeyEcho makes a sound each time the volume is changed. This sound is different to that of the usual keypress sound. It's a special sound (it was a special sound in v0.0.3 but now that I have updated to v0.0.4 that sound is just like a normal keypress sound) like how enter & space keys have their own unique sound. Since my scroll wheel is smooth, I don't really want a sound which I change the system volume. So I was wondering whether it would be possible to add a toggle that lets the user choose whether they want a KeyEcho response whenever they change the system volume. 

I hope this makes it clear. Thank you.

**Comment by ZacharyL2** [comment]
I'm sorry for the misunderstanding earlier.

I now understand your point clearly. Actually, KeyEcho doesn't produce sound feedback when users adjust the system volume.

The issue you encountered stems from [this line of code](https://github.com/ZacharyL2/KeyEcho/blob/master/src-tauri/src/keyecho/soundpack/sound.rs#L51). It defaults to emitting the sound of pressing the "A" key if there's no corresponding keyboard mapping. 

I'll fix this in an upcoming update. Thanks again for your feedback.

**Comment by ZacharyL2** [comment]
I fixed it in [v0.0.5](https://github.com/ZacharyL2/KeyEcho/releases/tag/v0.0.5).
