### ISSUE TITLE
[bug] Windows recognizes it as Trojan

### ISSUE THREAD

**Issue by virtual-thread** [ZacharyL2/KeyEcho#24]
### OS

Windows

### OS Version

Windows 11 Pro 23H2, OS build 22631.3800

### Describe the bug

After updating windows, app just disappeared from computer.
Popup appeared saying app is quarantined because it recognizes it as Trojan 
![Trojan quarantined](https://github.com/user-attachments/assets/3cc47b1e-aa4e-4ba0-a8a3-ebcbb112a298)

After trying to reinstall windows just installs it and I got popup that app is blocked because it recognizes it as Trojan 
![Trojan 1](https://github.com/user-attachments/assets/4e9723ed-9dc0-402f-b6ca-ce01333c8326)

**Comment by ZacharyL2** [comment]
Duplicated #18
