### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Joshf225** [ZacharyL2/KeyEcho#26]
### OS

MacOS

### OS Version

Version 14.5 (23F79)

### Describe the bug

the sound isnt working when i click on the mac keyboard, when i open the dashboard only the shift, option, command, and tab buttons make the sounds nothing else, and once i go out of the dashboard the sounds stop working on those buttons aswell

**Comment by ZacharyL2** [comment]
Please try removing KeyEcho from the Input Monitoring list and reinstalling it.

<img width="487" alt="339296976-4d62d705-4a7a-435b-b834-c8bb17e09b88" src="https://github.com/user-attachments/assets/ae0ae63d-f387-4b0c-b71e-d2a513ec3bb0">

**Comment by Joshf225** [comment]
Hi I did that and again it worked only when i had the dashboard opened, and it only wokred for the control,comman, and option keys rather than the whole keyboard

**Comment by ZacharyL2** [comment]
I didn't encounter the issue you mentioned on the MacOS. However, you can debug the source code on the problematic machine. See [here](https://github.com/ZacharyL2/KeyEcho/issues/15#issuecomment-2194712514) for details.

**Comment by dr-sahil** [comment]
Maybe other apps might be interfering? Trying disabling VS Code and iTerm.

**Comment by Joshf225** [comment]
disable them where?

**Comment by Joshf225** [comment]
Fixed it, I had to first give the app control over my device in accessibility , then I removeed and added the app to input monitoring. Thanks.

**Comment by ZacharyL2** [comment]
You fixed the original problem by granting Accessibility and Input Monitoring permissions. KeyEcho 1.0's macOS builds now have stable signing and notarization, which should reduce permission identity changes after updates. If you are still using KeyEcho, I would be interested to know whether those permissions stay in place after moving to v1.
