### ISSUE TITLE
mac error: "Keyecho is damaged and should be moved to trash"

### ISSUE THREAD

**Issue by jatins** [ZacharyL2/KeyEcho#3]
tried via the latest dmg release[0] and got this error when trying to run.

[0] https://github.com/ZacharyL2/KeyEcho/releases/tag/v0.0.2

**Comment by ZacharyL2** [comment]
This issue is because KeyEcho isn't code-signed for macOS yet. Please choose "Open Anyway" in "Security & Privacy".

**Comment by feep** [comment]
As mentioned on [HN](https://news.ycombinator.com/item?id=40623655), Mach-O 64-bit executable arm64 does not open.

I have not tried the amd64 as that poster did.

This is what I get:

```
❯ file ./KeyEcho.app/Contents/MacOS/KeyEcho
./KeyEcho.app/Contents/MacOS/KeyEcho: Mach-O 64-bit executable arm64

# open (or right click open from Finder) gives this dialog: `“KeyEcho.app” is damaged and can’t be opened. You should move it to the Trash.`

❯ open ./KeyEcho.app
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-128 "userCanceledErr" UserInfo={_LSLine=4129, _LSFunction=_LSOpenStuffCallLocal}

# `"userCanceledErr"` is from clicking cancel in that dialog.

# Oddly, running it this way works fine/ No idea why.

❯ ./KeyEcho.app/Contents/MacOS/KeyEcho
```

That’s all I know. Just pasting it in case you don’t have access to an ARM Mac.

**Comment by niklaskorz** [comment]
Remove the quarantine flag, then you can right-click open it:

```
xattr -d com.apple.quarantine KeyEcho.app
```

**Comment by feep** [comment]
__Note:__ this issue does not affect me. No rush. I am just providing feedback.

Do you have an ARM mac, @ZacharyL2?

> did you deny the "Input Monitoring" dialog when you first opened the application?

Nope. First thing on _any_ open method is the `“KeyEcho.app” is damaged and can’t be opened....` dialog. Including right-click.

**Comment by ZacharyL2** [comment]
@feep I don't have an ARM MacOS, and it seems unlikely that I can emulate it. Could you help test it?

```
Clone  -> pnpm i -> pnpm tauri dev
```

In theory, this ARM MacOS package is built by [tauri-action](https://github.com/tauri-apps/tauri-action) in the corresponding system environment, so it should not be usable on x86_64 but not on aarch64.

**Comment by ZacharyL2** [comment]
@feep Thanks for mentioning it. I have made the changes in [v0.0.3](https://github.com/ZacharyL2/KeyEcho/releases/tag/v0.0.3).

**Comment by feep** [comment]
Fixed for me.

Right click > Open in finder pops the dialog to allow from unknown dev (whatever it says).

Only tested with `KeyEcho_aarch64.app.tar.gz`.

Close, or wait for a confirmation from another ARM user.

As far as I am concerned, it is closed.

**Comment by ZacharyL2** [comment]
To centrally address issues caused by unsigned code, I have opened a new issue #18. Please continue to raise any questions there. I will close this issue. Thank you for your contribution!

**Comment by ZacharyL2** [comment]
The macOS “damaged and should be moved to trash” warning you reported came from the unsigned older build. KeyEcho 1.0's Intel and Apple Silicon builds are now signed with Developer ID, notarized, stapled, and verified before release. You can get the new build here: https://github.com/ZacharyL2/KeyEcho/releases/tag/v1.0.0. If the new DMG still shows the same warning, please share your macOS version and the exact filename.
