### ISSUE TITLE
[bug] Cannot Download the 'nk-cream' Sound Profile

### ISSUE THREAD

**Issue by shub-qantas** [ZacharyL2/KeyEcho#31]
### OS

MacOS

### OS Version

macOS Sequoia 15.1

### Describe the bug

Unable to download and use the  'nk-cream' sound profile. Currently seeing the below error message, even after "re-downloading" the sound profile:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/f399578a-ddef-48df-84bb-10135d88740c">

**Comment by entropie72** [comment]
According to [CustomSounds.md](https://github.com/ZacharyL2/KeyEcho/blob/master/CustomSounds.md), you need to go to **~/Library/Application Support/xyz.waveapps.keyecho/sounds**, create a folder named **nk-cream**, then copy **sound.ogg** and **config.json** into the newly created folder. Go back to KeyEcho and now you have it.
<img width="773" alt="SCR-20241125-dytu" src="https://github.com/user-attachments/assets/baeb71a2-0721-4328-8ef0-eb6712c13131">

**Comment by ZacharyL2** [comment]
KeyEcho 1.0 fixes the NK Cream download and directory layout. The new version creates the correct pack directory from the archive name, so there is no need to make an `nk-cream` folder manually. Thanks to `entropie72` for sharing the macOS workaround at the time. Please try v1, and if it still fails, post the app-data directory structure.
