### ISSUE TITLE
Can't download sounds on Windows 11

### ISSUE THREAD

**Issue by Klvxn** [ZacharyL2/KeyEcho#32]
### OS

Windows

### OS Version

11 23H2

### Describe the bug

Download failed error whenever I try to "Download from online"

**Comment by ZacharyL2** [comment]
KeyEcho 1.0 rewrote online sound-pack downloading and safe extraction, including the mismatch between archive names and destination directories. The original report did not include logs. If you are still on Windows 11, please try v1. If the download still fails, share the pack name, installer architecture, and a screenshot of the error.
