### ISSUE TITLE
"This app can't run on your PC"

### ISSUE THREAD

**Issue by tiagorangel2011** [ZacharyL2/KeyEcho#4]
On Windows 11 Pro Insider edition. I used the default -setup.exe file from the releases tab.

![image](https://github.com/ZacharyL2/KeyEcho/assets/70700766/46d1b09f-9daf-4d4a-9322-55a89f95c985)

**Comment by tiagorangel2011** [comment]
nvm I was using the arm64 version

**Comment by ZacharyL2** [comment]
KeyEcho 1.0 now has separate Windows x64 and ARM64 installers, both signed with Authenticode. The original report did not include the system architecture. If you are still able to test, please download the v1 installer that matches your device. If it still will not run, share the Windows build, CPU architecture, and installer filename.
