### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by emoss08** [ZacharyL2/KeyEcho#8]
You might want to fix this.

![image](https://github.com/ZacharyL2/KeyEcho/assets/66630775/eee3d984-8245-475a-9ec4-893e695798c9)

**Comment by ZacharyL2** [comment]
@emoss08 Hello, please provide your Windows information and the version of the KeyEcho you downloaded.

**Comment by emoss08** [comment]
Apologies the delay in this response.

windows 11 home, 10.0.22631 build 22631 and it was version 0.0.2, I see you released 0.0.3 I will try it out.

**Comment by emoss08** [comment]
0.0.3 fixes the issue, thankfully. Again, sorry for the delay. Love this app. Thank :)

**Comment by ZacharyL2** [comment]
You confirmed that 0.0.3 worked and mentioned that you liked the app. KeyEcho 1.0 is now available with an Authenticode-signed Windows installer that is verified before release. Thanks for helping confirm the early false-positive report. If you are still using Windows, I would be interested to know whether the new build produces fewer security warnings: https://github.com/ZacharyL2/KeyEcho/releases/tag/v1.0.0.
